apiversion: apps/v1
kind: StatefulSet
metedata:
  namespace: roboshop
  name: rabbitmq
  labels:
    tier: db
    service: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      service: rabbitmq
  template:
    metedata:
      labels: 
        tier: db
        service: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 3Gi
---
kind: Service
apiVersion: v1
metedata:
  name: rabbitmq
  namespace: roboshop
  labels:
    tier: db
    service: rabbitmq
spec:
  clusterIP: None
  selector:
    tier: db
    service: rabbitmq
  ports:
  - name: rabbitmq-amq
    protocol: TCP
    # service port
    port: 5672
    # pod port
    targetPort: 5672
  - name: rabbitmq-http
    protocol: TCP
    # service port
    port: 15672
    # pod port
    targetPort: 15672


