apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: mongodb 
  labels:
    tier: db
    service: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      service: mongodb
  template:
    metadata:
      labels:
        tier: db
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: saivinaylt/mongodb:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 3G
---
kind: Service
apiVersion: v1
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    tier: db
    service: mongodb
spec:
  clusterIP: None
  selector:
    tier: db
    service: mongodb
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017

