kind: ConfigMap
apiVersion: v1
metadata:
  namespace: roboshop
  name: mysql-configmap
data:
  MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
  MYSQL_DATABASE : cities
  MYSQL_USER : shipping
  MYSQL_PASSWORD : secret
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: mysql 
  labels:
    tier: db
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      service: mysql
  template:
    metadata:
      labels:
        tier: db
        service: mysql
    spec:
      containers:
      - name: mysql
        image: saivinaylt/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql-configmap
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic-sc"
      resources:
        requests:
          storage: 2G
---
kind: Service
apiVersion: v1
metadata: 
  namespace: roboshop
  name: mysql
  labels:
    tier: db
    service: mysql
    project: roboshop
spec:
  selector:
    tier: db
    service: mysql
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
    

