apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: redis
  labels: 
    tier: db
    service: redis
spec: 
  replicas: 1
  selector:
    matchLabels:
      tier: db
      service: redis
  template:
    metadata:
      labels:
        tier: db
        service: redis
    spec:
      containers:
      - image: redis
        name: redis
        volumeMounts:
        - name: rabbitmq
          mountPath: /data
  # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 2Gi
---
kind: Service
apiVersion: v1
metadata:
  namespace: roboshop
  name: redis
  labels:
    tier: db
    service: redis
spec:
  clusterIP: None
  selector:
    tier: db
    service: redis
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
